### ISSUE TITLE
Feedback for Movie-search-project (문승현 튜터)

### ISSUE THREAD

**Issue by bewisesh91** [jiyong89/Movie-search-project#1]
안녕하세요 :) 첫 개인 과제 제출 고생하셨습니다! 
기본 요구 사항은 모두 잘 구현하신 것 같습니다.

개인 과제 기본 구현 사항 체크
[1] jQuery 라이브러리 사용없이 순수 바닐라 자바스크립트 사용하기 👍 💯
[2] TMDB 오픈 API를 이용하여 인기영화 데이터 가져오기 👍 💯
[3] 영화정보 카드 리스트 UI 구현 👍 💯
[4] 영화 검색 UI 구현 👍 💯
[5] 하기 기재된 Javascript 문법 요소를 이용하여 구현 👍 💯

이외에 피드백드리고 싶은 점을 정리해보자면 다음과 같습니다.

1. 보안
- API Key 같은 경우, 직접적으로 코드에 작성하는 것은 위험할 수 있어요.
- 지금은 어쩔 수 없다고 하더라도, 중요한 Key 정보는 환경 변수로 관리하면 좋을 것 같습니다.

2. 불필요한 주석
- 코드에 불필요한 주석들을 삭제하면 좋을 것 같아요.
- 주석 없이도 충분히 이해할 수 있게 코드를 잘 작성하셨어요!ㅎㅎㅎ
- 제 생각에 주석없이 가독성있게 작성한 코드가 좋은 코드인 것 같아요.
- 앞으로도 주석 없이 코드를 작성하는 노력을 하면 좋을 것 같습니다.

3. 커밋 관리
- 현재 커밋을 한글로 작성하셨는데요.
- 사실 한글로 작성해도 무방하지만, 일반적으로는 영어로 작성을합니다.
- 또한, 커밋 이력 앞에 간단한 접두사들을 적어요.
- 이것은 팀/프로젝트마다 컨벤션이 달라서 상황에 따라 다르게 적용될 수 있지만 '일반적인' 기준에서 말씀드리는 것이오니 참고 부탁드립니다.

**Comment by jiyong89** [comment]
너무너무 감사합니다_환경변수 공부하겠습니다.!
